defmodule AshScimDemoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ash_scim_demo

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_ash_scim_demo_key",
    signing_salt: "CsF2XVqw",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Dispatch SCIM requests before Plug.Static (which rejects paths
  # containing `:`, like `/Schemas/urn:ietf:params:scim:schemas:core:2.0:User`).
  plug :scim_dispatch

  defp scim_dispatch(%Plug.Conn{path_info: ["scim", "v2" | rest]} = conn, _opts) do
    conn = %{conn | path_info: rest, script_name: conn.script_name ++ ["scim", "v2"]}
    conn |> AshScimDemoWeb.ScimRouter.call(AshScimDemoWeb.ScimRouter.init([])) |> Plug.Conn.halt()
  end

  defp scim_dispatch(conn, _opts), do: conn

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ash_scim_demo,
    gzip: not code_reloading?,
    only: AshScimDemoWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ash_scim_demo
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug AshScimDemoWeb.Router
end
