defmodule AshScimDemo.Repo.Migrations.AddUserEmails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_emails, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value, :text, null: false
      add :primary, :boolean, default: false
      add :type, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "user_emails_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end
  end

  def down do
    drop constraint(:user_emails, "user_emails_user_id_fkey")

    drop table(:user_emails)
  end
end
