defmodule AshScimDemo.Repo.Migrations.AddGroupsAndScim do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :email, :citext, null: false
      add :active, :boolean, default: true
      add :first_name, :text
      add :last_name, :text
      add :scim_external_id, :text
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :text, null: false
      add :group_id, :uuid, null: false
    end

    create unique_index(:memberships, [:user_id, :group_id],
             name: "memberships_user_in_group_index"
           )

    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :scim_external_id, :text
    end
  end

  def down do
    drop table(:groups)

    drop_if_exists unique_index(:memberships, [:user_id, :group_id],
                     name: "memberships_user_in_group_index"
                   )

    drop table(:memberships)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :scim_external_id
      remove :last_name
      remove :first_name
      remove :active
      remove :email
    end
  end
end
